name: isolated-modules

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bun:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [isolated, hoisted]
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v4

      - name: ğŸ— Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: ğŸ— Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: âš™ï¸ Configure Bun
        run: |
          git rm .npmrc pnpm-lock.yaml pnpm-workspace.yaml
          echo $(jq '.workspaces = ["apps/*","packages/*"]' package.json) > package.json

      - name: âš™ï¸ Configure isolation
        if: ${{ matrix.mode == 'isolated' }}
        run: |
          touch bunfig.toml
          echo "[install]" >> bunfig.toml
          echo "linker = \"isolated\"" >> bunfig.toml

      - name: ğŸ“¦ Install dependencies
        run: bun install

      - name: âœ… Lint packages
        run: bun run lint

      - name: ğŸ‘· Build packages
        run: bun run build

      - name: ğŸ§ª Test packages
        run: bun run test

  npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [isolated, hoisted]
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v4

      - name: ğŸ— Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: âš™ï¸ Configure npm
        run:
          git rm .npmrc
          echo $(jq '.workspaces = ["apps/*","packages/*"]' package.json) > package.json

      - name: ğŸ“¦ Install dependencies
        if: ${{ matrix.mode == 'isolated' }}
        run: npm install --install-strategy=linked

      - name: ğŸ“¦ Install dependencies
        if: ${{ matrix.mode == 'hoisted' }}
        run: npm install

      - name: âœ… Lint packages
        run: npm run lint

      - name: ğŸ‘· Build packages
        run: npm run build

      - name: ğŸ§ª Test packages
        run: npm run test


  pnpm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [isolated, hoisted]
    steps:
      - name: ğŸ— Setup repository
        uses: actions/checkout@v4

      - name: ğŸ— Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: âš™ï¸ Configure isolation
        if: ${{ matrix.mode == 'isolated' }}
        run: git rm .npmrc

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: âœ… Lint packages
        run: pnpm run -w lint

      - name: ğŸ‘· Build packages
        run: pnpm run -w build

      - name: ğŸ§ª Test packages
        run: pnpm run -w test
